### ISSUE TITLE
set-gspeak.sh won't update references in the project's README or main.cpp

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi-greenhouse#3]
References to the g-speak version at scaffold time:

https://github.com/Oblong/obi-greenhouse/blob/master/templates/README.md#build

and

https://github.com/Oblong/obi-greenhouse/blob/master/templates/main.cpp#L4

will not be updated after committing the results of `set-gspeak.sh`. It'd be nice if the script would update those locations, too.

**Comment by sandover** [comment]
It's beyond the scope of set-gspeak.sh to do this kind of thing.  set-gspeak.sh is an artifact of our buildbot and isn't really intended for developers to even use directly.  We shouldn't assume that it exists or expect it to do anything except provide some help at debian packaging time.

**Comment by dankegel** [comment]
It's not an artifact of our buildbot at all, but rather an artifact
of the fact that we use debian packaging tools, which require
dependencies to be valid before running cmake or anything.

That said, it's more trouble than it's worth to have it adjust README's.

**Comment by sandover** [comment]
Yes, that's better said -- a tool for packaging.  Packaging and READMEs are orthogonal.

**Comment by tomjakubowski** [comment]
Okeydokey.
