### ISSUE TITLE
obi new greenhouse fails if libWebThing is not installed 

### ISSUE THREAD

**Issue by EchoAbstract** [Oblong/obi-greenhouse#7]
When attempting to create a new greenhouse project (where I'm going to remove WebThing from the CMakeLists.txt), `obi new` fails because I don't have 3.29's libWebThing installed:

```
Found /opt/oblong/g-speak3.29 by directory lookup
Traceback (most recent call last):
  File "/usr/local/Cellar/obi/HEAD-a6265cd/libexec/bin/obi", line 11, in <module>
    load_entry_point('oblong-obi==3.2.1', 'console_scripts', 'obi')()
  File "/usr/local/Cellar/obi/HEAD-a6265cd/libexec/lib/python2.7/site-packages/obi/obi.py", line 171, in main
    g_speak_version=g_speak_version)
  File "/Users/bwilson/.local/share/oblong/obi/greenhouse/greenhouse.py", line 57, in obi_new
    kwargs['cef_branch'] = get_cef_branch(kwargs['g_speak_version'])
  File "/Users/bwilson/.local/share/oblong/obi/greenhouse/greenhouse.py", line 41, in get_cef_branch
    with open("/opt/oblong/g-speak%s/lib/pkgconfig/libWebThing.pc" % g_speak_version, 'r') as f:
IOError: [Errno 2] No such file or directory: '/opt/oblong/g-speak3.29/lib/pkgconfig/libWebThing.pc'
```

The python code seems to think that this is handled (https://github.com/Oblong/obi-greenhouse/blob/master/greenhouse.py#L47-L49), but that case is only triggered if we can open `/opt/oblong/g-speak3.29/lib/pkgconfig/libWebThing.pc`, not if the file doesn't exist.

**Comment by Gobiner** [comment]
I added a check for the existence of libWebThing.pc before the template tries to read it. 42b24e2dc014003bae6e8f3572ba144b885aa8e8
It fixes this issue on my machine.

**Comment by sandover** [comment]
@EchoAbstract could you test?

**Comment by EchoAbstract** [comment]
I will test when I get a chance, I don't currently have any installs without libWebthing, I'll need to setup a test environment.

**Comment by Gobiner** [comment]
![image](https://user-images.githubusercontent.com/372839/27704769-85d610e2-5cc0-11e7-9d68-fe7d26668856.png)
